export const subreddits = ['memes', 'meme', 'dankmemes', 'Memes_Of_The_Dank', 'me_irl'];
export const captions = [
  "#meme #memes #funny #dankmemes #dank #lol #lmao #dank #funnymemes #memesdaily #dankmeme #f #dankmemes #follow #cringe #like #lmfao #anime #hilarious #comedy #offensivememes #fortnite #filthyfrank #nichememes #offensive #jokes #l #bhfyp",
  "#meme #memes #bestmemes #instamemes #funny #funnymemes #dankmemes #offensivememes #edgymemes #spicymemes #nichememes #memepage #funniestmemes #dank #memesdaily #jokes #memesrlife #memestar #memesquad #humor #lmao #igmemes #lol #memeaccount #memer #relatablememes #funnyposts #sillymemes #nichememe #memetime",
  "#memes #meme #funny #dankmemes #funnymemes #memesdaily #follow #lol #instagram #humor #like #tiktok #ol #dank #viral #comedy #explorepage #bhfyp #instagood #dailymemes #memepage #fun #memestagram #offensivememes #edgymemes #followforfollowback #lmao",
  "#memes #meme #funny #memesdaily #dankmemes #funnymemes #lol #love #dank #comedy #lmao #fortnite #humor #edgymemes #instagood #fun #dankmeme #music #edgy #anime #offensivememes #art #instagram #cringe #bhfyp #hilarious #funnyvideos #photography #explore #photooftheday",
  "#funny #memes #lol #meme #dankmemes #comedy #funnymemes #memesdaily #dank #edgymemes #offensivememes #memestagram #memes😂 #memes4ever #memes4life #memessad #funnymemes😂 #memesarelife #mememachine #bestmeme #memesinstagram #memeking #memesdaily😂 #memestealer #shrekmemes #dankmemer #hillarious #funmeme #memestwitter #memessimpsons",
  "#memes #dankmemes #offensivememes #memes4life #qualitymemes #memesaremee #kermitmemes #darkhumormemes #coolmemes #soccermemes #loveandaffectionmemes #memesday #memesforteens #dankmemes2k17 #memestagramm #newmeme #memespage",
  "#memes #meme #funny #memesdaily #dankmemes #funnymemes #lol #love #dank #comedy #follow #lmao #fortnite #humor #like #edgymemes #instagood #fun #dankmeme #music #edgy #anime #offensivememes #art #instagram #cringe #bhfyp #hilarious #funnyvideos #photography",
  "#memes #meme #dankmemes #lmao #dank #filthyfrank #cringe #edgy #lmfao #fnaf #papafranku #kek #nochill #relatable #ayylmao #hilarious #4chan #savage #weeaboo #triggered #pepe #mlg #funnymemes #bushdid911 #comedy #textposts #minecraft #spongebob",
  "#spicymemes #relatableaf #relatablepost #memestagram #dankmemes #relatabletweets #relatablememes #relatablememe #relatable #memepage #funnymeme #memedaily #animememes #sorelatable #memeaccount #memez #relatablequote #meme #relatableposts #memesdaily #memes😂 #memes #relatabletextposts #relatables #funnymemes #relatabletextpost #dankmeme #memesfordays #memer #relatablequotes",
  "#memes #dankmemes #dailymemes #funnymemes #nichememes #jokes #laugh #edgymemes #comedy #spicymemes #memestagram #wholesomememes #dankmemesdaily #follow #humor #funny #fun #bestmemes #haha #offensivememes #memesdaily #instagood #viral #memer #like #meme #memes😂 #lol",
  "#funny #funnymeme #lol #lmao #funnyvideo #funnyvideos #funnypost #funnyshit #haha #joke #instagood #funnyposts #meme #funnyaf #comedy #funnypictures #instagram #funnyquotes #funnymemes #dankmemes #humor #memes #dank #funnymoments #funnypics",
];
export const FACEBOOK_APP_ID = "1098645864366196"; // Find your App ID in the App Dashboard on Facebook for Developers.
export const INSTAGRAM_PAGE_ID = '17841417742728074';